---
title: "ExamenII_G1_C4J618_Liz_Salazar"
author: "Liz de María Salazar Amaya"
date: 11-30-2025
format: 
  html:
    toc: true
    theme: cosmo
    self-contained: true
    toc-float: true
---

# Parte de R

Link del repositorio: https://github.com/lizsalazar17/ExamenII_G1_C4J618.git

Primero, cargaremos la data de moras.txt


```{r}
library(readr)
library(dplyr)

df <- read_csv("../data/moras.txt")
head(df)


```


## 1. Resumen de 5 números

Para edad: 
```{r}

df %>%
  summarise(
    Categoria = "Edad",
    Media = mean(EDAD, na.rm = TRUE),
    Mediana = median(EDAD, na.rm = TRUE),
    Desviacion = sd(EDAD, na.rm = TRUE),
    Minimo = min(EDAD, na.rm = TRUE),
    Maximo = max(EDAD, na.rm = TRUE),
  )
df %>% 
  summarise(
    Categoria = "Salario",
    Media = mean(SALARIO, na.rm = TRUE),
    Mediana = median(SALARIO, na.rm = TRUE),
    Desviacion = sd(SALARIO, na.rm = TRUE),
    Minimo = min(SALARIO, na.rm = TRUE),
    Maximo = max(SALARIO, na.rm = TRUE),
  ) 
  
  
```
  ## 3-Valores atípicos
  
```{r}
  promedio.edad <- mean(df$EDAD, na.rm = TRUE)
  desviacion.edad <- sd(df$EDAD, na.rm = TRUE)
  
  promedio.salario <- mean(df$SALARIO, na.rm = TRUE)
  desviacion.salario<- sd(df$SALARIO, na.rm = TRUE)

df.modificada <- 
df %>% 
  mutate (
    Z_SCORE_EDAD= (EDAD - promedio.edad) / desviacion.edad,
    VALORES_ATIPICOS_EDAD = ifelse(abs(Z_SCORE_EDAD) > 1.69, "SI", "NO"),
    Z_SCORE_SALARIO= (EDAD - promedio.salario) / desviacion.salario,
    VALORES_ATIPICOS_SALARIO = ifelse(abs(Z_SCORE_SALARIO) > 1.69, "SI", "NO")
  )

head(df.modificada)
```
  
  ## 4. Valores faltantes 

    
```{r}
valores.nulos <- colSums(is.na(df.modificada))
tamanio <- nrow(df.modificada)
porcentaje.por.columna <- valores.nulos / tamanio * 100
porcentaje.por.columna
```
  ## 5. Imputación de datos
```{r}
  mediana.edad <- median(df$EDAD, na.rm = TRUE)
  mediana.salario <- median(df$SALARIO, na.rm = TRUE)
  moda.tipo <- df %>%
      count(TIPO_ASEGURAMIENTO) %>%
      arrange(desc(n)) %>%
      slice(1) %>%
      pull(TIPO_ASEGURAMIENTO)


df.modificada <- df.modificada %>%
  mutate(
    EDAD = if_else(
      is.na(EDAD),
      mediana.edad,
      EDAD
    ),
    SALARIO = if_else(
      is.na(SALARIO),
      mediana.salario, 
      SALARIO
    ), 
    TIPO_ASEGURAMIENTO = if_else(
      is.na(TIPO_ASEGURAMIENTO), 
      moda.tipo, 
      TIPO_ASEGURAMIENTO
    )
  )


```
  
  #6. Gráficos de individuos por categoría

  
  